"""empty message

Revision ID: c9e1bb8e5308
Revises: None
Create Date: 2017-07-03 10:32:28.832558

"""

# revision identifiers, used by Alembic.
revision = 'c9e1bb8e5308'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashtag', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twitteruser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screen_name', sa.String(length=100), nullable=False),
    sa.Column('uid', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hashtag_user',
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['twitteruser.id'], )
    )
    op.create_table('tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweet', sa.String(length=300), nullable=False),
    sa.Column('tid', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coordinates', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=100), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['twitteruser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hashtag_tweet',
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtag.id'], ),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweet.id'], )
    )
    op.create_table('tweet_word',
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweet.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet_word')
    op.drop_table('hashtag_tweet')
    op.drop_table('tweet')
    op.drop_table('hashtag_user')
    op.drop_table('word')
    op.drop_table('twitteruser')
    op.drop_table('hashtag')
    # ### end Alembic commands ###
